name: CI (No Test)

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-only:
    name: Build Spring Boot (No Test)
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      # 1. 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. gradlew 실행 권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. 테스트 제외하고 빌드만 수행
      - name: Build without tests
        run: ./gradlew build -x test

  dependency-submission:
    name: Submit Dependency Graph
    runs-on: ubuntu-22.04
    needs: build-only
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Submit dependency graph
        uses: gradle/actions/dependency-submission@v4
